server.port=9090

spring.data.redis.url=redis-12908.c301.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=12908
spring.data.redis.username=default
spring.data.redis.password=N1XkdvAVTyuI6ax8CKpfx1HqYpyq2XRb