spring:
  application:
    name: Greet-api
  boot:
    admin:
      client:
        url: htpp://localhost:9090/
server:
  port: 2222

management:
  endpoints:
    web:
      exposure:
        include: '*'